DESC MEDIVAC.ROUTES;

SELECT * FROM MEDIVAC.ROUTES;

INSERT INTO `MEDIVAC`.`ROUTES`
(`NAME`,
`PLACE_FROM`,
`PLACE_TO`,
`PRICE`,
`TIME`,
`CAR`)
VALUES
('FIRST GOLD EXPRESS ROUTE','DRAGON SHRINE','HANAMURA TEMPLE',100,'2021-09-21 12:20:00',
(SELECT ID
	FROM MEDIVAC.CAR
        WHERE id = 1));

COMMIT;